import "./globals.css";
import Link from 'next/link';
import styles from './home.module.css';

import { redirect } from 'next/navigation';

export const metadata = {
  title: "bwng",
  description: "Generated by create bwng0v0",
};

export default function RootLayout({children}) {
  return (
    <html>
      <body>
      {/* redirect('/home'); */}

      <div className={styles.nav}>
      <div className={styles.navleft}><Link href="/"><>bwng0v0</></Link></div>
      <div className={styles.navright}><Link href="/blog">blog</Link><Link href="/profile">profile</Link></div>
      </div>  

        {children}

      <div className={styles.footer}>
      <div>ⓒ bwng0v0, All Rights Reserved.</div>
      </div>


      {/* <div id="mouse-cursor">
        <div></div>
      </div> */}

      
      </body>
    </html>
  );
}